server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: ajaz@amu786
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
